all: ctarget/target/release/libcuriefense.so

ctarget:
	mkdir ctarget

ctarget/registry: ctarget
	mkdir -p ctarget/registry

ctarget/target: ctarget
	mkdir -p ctarget/target

ctarget/target/release/libcuriefense.so: container ctarget/registry ctarget/target
	docker run -v `pwd`:/home/builder/rust -v `pwd`/ctarget/registry:/home/builder/.cargo/registry  -w /home/builder/rust  -t curiefense/rustbuild:latest /home/builder/.cargo/bin/cargo build --release --target-dir ctarget/target

../lua/shared-objects/curiefense.so: ctarget/target/release/libcuriefense.so
	cp ctarget/target/release/libcuriefense.so ../lua/shared-objects/curiefense.so

.PHONY: all container test test-nodeps

container:
	tar c Dockerfile  |  docker build -t curiefense/rustbuild -f Dockerfile -

test: ctarget/target/release/libcuriefense.so test-nodeps
	echo DONE

test-nodeps:
	docker run -v `pwd`/ctarget/target/release/libcuriefense.so:/usr/local/lib/lua/5.1/curiefense.so \
						 -v `pwd`/../lua:/home/builder/lua \
						 -v `pwd`/../lua/shared-objects/luahs.so:/usr/local/lib/lua/5.1/luahs.so \
						 -v `pwd`/../lua/shared-objects/libinjection.so:/usr/local/lib/lua/5.1/libinjection.so \
						 -v `pwd`/../lua/shared-objects/grasshopper.so:/usr/local/lib/lua/5.1/grasshopper.so \
						 -v `pwd`/../../images/confserver/bootstrap/confdb-initial-data/master/config:/config/current/config \
						 -v `pwd`/luatests/test.lua:/home/builder/test.lua \
						 -v `pwd`/luatests/run.sh:/home/builder/run.sh \
						 -v `pwd`/luatests/config/json:/config/current/config/json \
						 -v `pwd`/luatests:/home/builder/luatests \
						 -w /home/builder -t curiefense/rustbuild:latest \
						 /bin/sh /home/builder/run.sh