{
 "title": "Top Activities",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Top Countries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum( rate(curiemetric_session_details_total[5m])) by (geo))",
     "legendFormat": "{{ geo }}"
    }
   ]
  },
  {
   "title": "Top URLMaps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum( rate(curiemetric_session_details_total[5m])) by (urlmap))",
     "legendFormat": "{{ geo }}"
    }
   ]
  },
  {
   "title": "Top URLs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum( rate(curiemetric_session_details_total[5m])) by (path))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Methods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum( rate(curiemetric_session_details_total[5m])) by (method))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Blocked Methods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum( rate(curiemetric_session_details_total[5m])) by (method))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Blocking WAF IDs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum( rate(curiemetric_session_details_total[5m])) by (wafid))",
     "legendFormat": "{{ wafid }}"
    }
   ]
  },
  {
   "title": "Blocking ACL IDs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum( rate(curiemetric_session_details_total[5m])) by (aclname))",
     "legendFormat": "{{ aclname }}"
    }
   ]
  }
 ]
}