name: Manual publish docker images

on:
  workflow_dispatch

jobs:
  push:
    runs-on: ubuntu-latest

    environment: prod
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build and push the images
        run: |
            docker login -u "${{ secrets.DOCKER_HUB_USER }}" -p "${{ secrets.DOCKER_HUB_PASSWORD }}"
            pushd curiefense/images
            export DOCKER_TAG=$(echo ${GITHUB_REF#refs/heads/})
            PUSH=1 ./build-docker-images.sh

            export DOCKER_TAG=${GITHUB_SHA}
            PUSH=1 ./build-docker-images.sh
